import { Navbar } from "@/components/common/navbar";
import type { Metadata } from "next";
import "./globals.css";
import './satoshi.css';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-s-regular antialiased`}
      >
        <Navbar />
        {children}

      </body>
    </html>
  );
}
